services:
  3lakustinizer-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    container_name: 3lakustinizer-frontend
    ports:
      - "3000:3000"
    restart: always